<template>
    <aside class="sidebar">
        <ul>
            <li>
                1.指令
            </li>
            <li>
                2.过滤器
            </li>
            <li>
                3.渲染列表
            </li>
            <li>
                4.事件监听
            </li>
            <li>
                5.处理表单
            </li>
            <li>
                6.计算属性
            </li>
            <li>
                7.自定义指令
            </li>
            <li>
                8.自定义过滤器
            </li>
            <li>
                9.组件系统
            </li>
            <li>
                10.过渡效果
            </li>
        </ul>
    </aside>
</template>

<script>

</script>